"""
Preprocessing module (Python implementation of src/lib/algorithm/preprocess.ts)
Maintains 1:1 preprocessing parity between Python training loader and TS runtime adapter.
"""

import re

# URL pattern: matches http://, https://, www., and domain-like patterns.
URL_PATTERN = re.compile(r"https?://\S+|www\.\S+", re.IGNORECASE)
# Mention/tag pattern: matches @username or similar tags.
TAG_PATTERN = re.compile(r"@\w+")
# Hashtag pattern: matches #hashtag.
HASHTAG_PATTERN = re.compile(r"#\w+")
# Emoji pattern: matches unicode emoji sequences.
EMOJI_PATTERN = re.compile(
    r"[\U0001F300-\U0001F9FF]|[\u2600-\u27BF]|[\U0001F000-\U0001F02F]|[\U0001F0A0-\U0001F0FF]|[\u2300-\u23FF]|[\u2000-\u206F]"
)

# Pattern to detect letters repeated 3 or more times.
REPETITION_PATTERN = re.compile(r"([a-zA-Z])\1{2,}")

# Extracted from common feedback patterns in educational contexts (English + Tagalog/Taglish).
ABBREVIATION_MAP = {
    "asap": "as soon as possible",
    "ass": "assignment",
    "assgn": "assignment",
    "b4": "before",
    "bc": "because",
    "bkit": "bakit",
    "btw": "by the way",
    "clt": "cognitive load theory",
    "d2": "dito",
    "fyi": "for your information",
    "grp": "group",
    "hw": "homework",
    "idk": "i do not know",
    "iirc": "if i recall correctly",
    "ilo": "intended learning outcome",
    "imo": "in my opinion",
    "kc": "kasi",
    "lng": "lang",
    "lol": "laughing out loud",
    "mmya": "mamaya",
    "ngl": "not gonna lie",
    "pls": "please",
    "pra": "para",
    "prof": "professor",
    "proj": "project",
    "r": "are",
    "rbt": "revised bloom taxonomy",
    "recit": "recitation",
    "req": "requirement",
    "rn": "right now",
    "san": "saan",
    "sem": "semester",
    "smh": "shaking my head",
    "sna": "sana",
    "tbc": "to be confirmed",
    "tbf": "to be fair",
    "tbh": "to be honest",
    "thx": "thanks",
    "tlga": "talaga",
    "tti": "teaching through interactions",
    "ttm": "teaching through modeling",
    "u": "you",
    "ur": "your",
    "w/": "with",
    "w/o": "without",
    "wrt": "with respect to",
    "q": "ko",
    "p": "po",
    "lmao": "laughing my ass off",
}

ABBREVIATION_LOOKUP = {k.lower(): v for k, v in ABBREVIATION_MAP.items()}

# Double-letter vocabulary consulted by normalize_vowels to decide whether a
# repeated run collapses to one copy or keeps two.
SEED_VOCABULARY = {
    "aabutin",
    "aaccept",
    "aadd",
    "aagree",
    "aakalang",
    "aalign",
    "aalinlangan",
    "aama",
    "aantay",
    "aaral",
    "aaralan",
    "aaralin",
    "aargue",
    "aasa",
    "aasahang",
    "aasar",
    "aasikasuhin",
    "aask",
    "aassess",
    "aay",
    "aayos",
    "aayusin",
    "abbreviation",
    "abbreviations",
    "accent",
    "accept",
    "acceptable",
    "accepted",
    "access",
    "accessed",
    "accessibility",
    "accidentally",
    "accommodates",
    "accomplish",
    "accomplished",
    "accounting",
    "accuracy",
    "accurate",
    "across",
    "actually",
    "add",
    "added",
    "adder",
    "adding",
    "addition",
    "additional",
    "address",
    "addresses",
    "addressing",
    "adds",
    "affect",
    "affected",
    "affecting",
    "affects",
    "afternoon",
    "aggravating",
    "aggregation",
    "aggressively",
    "agree",
    "agreeing",
    "agrees",
    "ahahhaha",
    "ahhahaah",
    "ahhahaha",
    "ahhahahah",
    "ahhahahahah",
    "all",
    "allocation",
    "allotment",
    "allow",
    "allowed",
    "angarrogant",
    "anggulo",
    "angimpossible",
    "anliit",
    "announcement",
    "announcements",
    "annoy",
    "annoyed",
    "annoying",
    "antaas",
    "app",
    "appeal",
    "appearance",
    "appeared",
    "appears",
    "applicable",
    "application",
    "applications",
    "applied",
    "applies",
    "apply",
    "applying",
    "appreaciate",
    "appreciate",
    "appreciated",
    "appriceate",
    "approach",
    "approachable",
    "approaches",
    "approved",
    "apps",
    "arrange",
    "arrangement",
    "array",
    "arrays",
    "arrive",
    "arrived",
    "arrogance",
    "arrogant",
    "arrogante",
    "arrow",
    "arrowheads",
    "arrows",
    "ass",
    "assay",
    "assemble",
    "assemblers",
    "assembling",
    "assembly",
    "assertive",
    "assertiveness",
    "assess",
    "assessment",
    "assessments",
    "asset",
    "assets",
    "assign",
    "assigned",
    "assignment",
    "assignments",
    "assigns",
    "assistance",
    "assistant",
    "assistants",
    "associate",
    "associated",
    "association",
    "associations",
    "associative",
    "assume",
    "assumed",
    "assumption",
    "asymmetric",
    "attach",
    "attempt",
    "attempts",
    "attend",
    "attendance",
    "attention",
    "attitude",
    "attractive",
    "attribute",
    "attributes",
    "automatically",
    "backpressure",
    "ballpen",
    "barrier",
    "basically",
    "been",
    "beginner",
    "beginners",
    "beginning",
    "better",
    "between",
    "bigger",
    "biggest",
    "biglaan",
    "biglaang",
    "bills",
    "binabanggit",
    "binanggit",
    "binayaan",
    "biweekly",
    "blessing",
    "bloody",
    "bloom",
    "blurred",
    "book",
    "books",
    "boolean",
    "borrow",
    "boss",
    "bottom",
    "breezed",
    "bubble",
    "bubuuin",
    "buffer",
    "bullet",
    "business",
    "button",
    "buttons",
    "buuin",
    "buzz",
    "buzzing",
    "caffeine",
    "caffene",
    "call",
    "called",
    "calls",
    "cancelled",
    "canned",
    "cannot",
    "career",
    "cartoons",
    "ccs",
    "cell",
    "cellphone",
    "challenge",
    "challenges",
    "challenging",
    "chatter",
    "chatting",
    "chill",
    "choose",
    "choosing",
    "cinoconnect",
    "class",
    "classes",
    "classification",
    "classmate",
    "classmates",
    "classroom",
    "classs",
    "clueless",
    "coffee",
    "cohesiveness",
    "collab",
    "collaborate",
    "collaborating",
    "collaboration",
    "collaborative",
    "collection",
    "college",
    "collision",
    "collisions",
    "command",
    "commands",
    "comment",
    "commenting",
    "comments",
    "commerce",
    "commercial",
    "commincation",
    "commits",
    "committed",
    "common",
    "commonality",
    "commonly",
    "communicate",
    "communication",
    "completeness",
    "compress",
    "compressed",
    "compression",
    "conceed",
    "conceptually",
    "concurrency",
    "connect",
    "connected",
    "connectedness",
    "connecting",
    "connection",
    "connections",
    "connectors",
    "connects",
    "controlled",
    "controlling",
    "cooked",
    "cookie",
    "cookies",
    "cool",
    "cooperation",
    "coordinate",
    "coordinated",
    "coourse",
    "correct",
    "correction",
    "corrections",
    "correctly",
    "correlation",
    "crammed",
    "cross",
    "crossing",
    "css",
    "current",
    "currently",
    "curriculum",
    "cutting",
    "dadaan",
    "dataase",
    "debuggin",
    "debugging",
    "deep",
    "deeper",
    "deeply",
    "degree",
    "depression",
    "differ",
    "differed",
    "difference",
    "different",
    "differential",
    "differentiate",
    "differently",
    "difficult",
    "difficulty",
    "dinaan",
    "dinadaan",
    "dinidicuss",
    "dinidiscuss",
    "diniduscuss",
    "diniscuaa",
    "diniscuss",
    "dinisduss",
    "dinisuss",
    "directionless",
    "disagree",
    "disappoint",
    "disappointed",
    "disappointing",
    "disconnected",
    "discuss",
    "discussed",
    "discussing",
    "discussion",
    "discussions",
    "dismissed",
    "dismissive",
    "dollars",
    "doon",
    "door",
    "dragged",
    "dragging",
    "dropped",
    "drracket",
    "dull",
    "dumaan",
    "dumadaan",
    "dynamically",
    "eedit",
    "eeffort",
    "eencourage",
    "eevaluate",
    "eexplain",
    "effect",
    "effective",
    "effectively",
    "effects",
    "efficiency",
    "efficient",
    "efficiently",
    "effort",
    "efforts",
    "eggshells",
    "embarassment",
    "embarrass",
    "embarrassed",
    "embedded",
    "embeddings",
    "emotionally",
    "enggage",
    "engganyo",
    "engineer",
    "engineering",
    "enroll",
    "equally",
    "equipped",
    "error",
    "errors",
    "especially",
    "essay",
    "essentially",
    "euuuhhh",
    "eventually",
    "excellent",
    "express",
    "expression",
    "expressions",
    "exxplanation",
    "facebook",
    "fairness",
    "fall",
    "falls",
    "feedback",
    "feel",
    "feeling",
    "feels",
    "fell",
    "fellow",
    "ffeeling",
    "fifteen",
    "fill",
    "filled",
    "filler",
    "filling",
    "fills",
    "finally",
    "firewall",
    "firewalls",
    "follow",
    "followed",
    "following",
    "followup",
    "food",
    "fooled",
    "fools",
    "foot",
    "forgotten",
    "formatting",
    "free",
    "freely",
    "freeze",
    "full",
    "fully",
    "fundamentally",
    "funnier",
    "funny",
    "fuzzy",
    "gaano",
    "gaanong",
    "ganoon",
    "gcc",
    "generally",
    "geometrically",
    "getting",
    "gibberish",
    "giggling",
    "gonna",
    "good",
    "goods",
    "google",
    "gossip",
    "gossiping",
    "gotta",
    "gotten",
    "gradebook",
    "grammar",
    "grammars",
    "grammatical",
    "greedy",
    "greek",
    "guess",
    "guessing",
    "hahaaha",
    "hahahahaa",
    "hahahahhaha",
    "hahahha",
    "hahatiin",
    "hahhah",
    "hahhaha",
    "hahhahaa",
    "hahhahah",
    "hahhahhaaha",
    "hall",
    "handwritten",
    "hangganan",
    "hanggang",
    "happen",
    "happened",
    "happening",
    "happens",
    "happy",
    "hassle",
    "heartless",
    "hell",
    "hello",
    "hhahahaah",
    "hhahahah",
    "hhhahahaha",
    "hhrap",
    "highschool",
    "hinayaan",
    "hinuhulaan",
    "hmm",
    "hood",
    "horrible",
    "horribly",
    "http",
    "https",
    "hulaaan",
    "hulaan",
    "humming",
    "humulaan",
    "iaaccept",
    "iaanalyze",
    "iaanswer",
    "iaapply",
    "iaccept",
    "iapply",
    "iappreciate",
    "iapproach",
    "iconnect",
    "ididiscuss",
    "idinidiin",
    "idiscuss",
    "iduscuss",
    "ieelaborate",
    "ieencode",
    "ieexplain",
    "ifollow",
    "iiimplement",
    "iiimprove",
    "iilan",
    "iimbak",
    "iimpake",
    "iimplement",
    "iimport",
    "iimprove",
    "iincorporate",
    "iingat",
    "iingay",
    "iinitiate",
    "iinsist",
    "iintegrate",
    "iinteract",
    "iintindihin",
    "iintroduce",
    "iinvalidate",
    "iirap",
    "iisa",
    "iisang",
    "iisip",
    "iisipan",
    "iisipin",
    "iiupdate",
    "illustrations",
    "immature",
    "immediate",
    "immediately",
    "immutable",
    "impossible",
    "impressed",
    "impression",
    "inaabangan",
    "inaabot",
    "inaaccept",
    "inaagree",
    "inaalala",
    "inaallow",
    "inaamin",
    "inaanalyze",
    "inaanxiety",
    "inaaral",
    "inaasa",
    "inaasahan",
    "inaasahang",
    "inaassign",
    "inaassume",
    "inaassumme",
    "inaayos",
    "inappropriate",
    "inassign",
    "inassume",
    "incorrect",
    "indifferent",
    "individually",
    "ineemphasize",
    "ineenjoy",
    "ineexpand",
    "ineexpect",
    "ineexplain",
    "infairness",
    "iniignore",
    "iniigone",
    "iniinclude",
    "iniintegrate",
    "iniinvalidate",
    "iniinvite",
    "iniisip",
    "iniisipi",
    "iniiskip",
    "iniispend",
    "iniiwan",
    "iniiwang",
    "iniiwasan",
    "inilaan",
    "ininterrupt",
    "initially",
    "inoobserve",
    "inooffer",
    "inooverwhelm",
    "inoverlook",
    "installed",
    "instill",
    "insufficient",
    "intellectual",
    "intelligence",
    "intelligent",
    "interconnected",
    "interconnections",
    "interrupt",
    "interrupting",
    "intindihiin",
    "inuubos",
    "inuulit",
    "inuuna",
    "inuunahan",
    "inuupload",
    "inuutusang",
    "ioorganize",
    "ipafeel",
    "ipafill",
    "ipagtanggol",
    "irrelevant",
    "irritate",
    "irritated",
    "irritating",
    "isinasaalang",
    "issue",
    "issues",
    "isupport",
    "isusuggest",
    "itoss",
    "iuunite",
    "kaalaman",
    "kaantok",
    "kaawa",
    "kaaya",
    "kaayusan",
    "kabuuan",
    "kabuuang",
    "kaconnected",
    "kalagitnaan",
    "kapressure",
    "kastress",
    "kataas",
    "keep",
    "keeping",
    "keeps",
    "kill",
    "killing",
    "kinaligtaan",
    "kinoconnect",
    "kko",
    "latter",
    "legge",
    "less",
    "lesson",
    "lessons",
    "letters",
    "liliit",
    "linggo",
    "linggong",
    "literally",
    "little",
    "ll",
    "logging",
    "logically",
    "loob",
    "look",
    "looked",
    "looking",
    "looks",
    "loop",
    "looping",
    "loops",
    "lumiliit",
    "maaabot",
    "maaadjust",
    "maaapply",
    "maaari",
    "maaasahang",
    "maabot",
    "maabsord",
    "maabutan",
    "maaccept",
    "maacept",
    "maachieve",
    "maaddress",
    "maaga",
    "maalala",
    "maalam",
    "maalign",
    "maam",
    "maapply",
    "maappreciate",
    "maapreciate",
    "maayos",
    "maccept",
    "maconnect",
    "madedepress",
    "madidiscuss",
    "madifferentiate",
    "maeenjoy",
    "maeexcite",
    "mafeel",
    "maffreeze",
    "mafollow",
    "magaan",
    "magadd",
    "magarrange",
    "magborrow",
    "magcocomment",
    "magcoordinate",
    "magdiscuss",
    "mageexplain",
    "magfofollow",
    "magfollow",
    "maggets",
    "maggive",
    "maggrade",
    "magguide",
    "magiimprove",
    "magiiwan",
    "magjjump",
    "magkakaroon",
    "magkaroon",
    "maglaan",
    "maglalaan",
    "magproceed",
    "magsskip",
    "magsstart",
    "magsstruggle",
    "magsuggest",
    "magvolunteer",
    "magwoworry",
    "maiaambag",
    "maiaapply",
    "maiconnect",
    "maiintindihan",
    "maiiwasan",
    "maisaayos",
    "makaadjust",
    "makakeep",
    "makaligtaan",
    "makapagcollab",
    "makapagcollaborate",
    "makatanggap",
    "makeep",
    "makicollab",
    "makipagcommunicate",
    "maliit",
    "maliitin",
    "maliliit",
    "malloc",
    "mangmaliit",
    "manner",
    "manonood",
    "manood",
    "manually",
    "mapagmataas",
    "mapaiinis",
    "mapped",
    "mapping",
    "marecall",
    "massive",
    "mataas",
    "matandaan",
    "matanggap",
    "mathematically",
    "matter",
    "matters",
    "maunawaan",
    "meet",
    "meeting",
    "meetings",
    "mess",
    "message",
    "messaged",
    "messages",
    "messaging",
    "messenger",
    "messes",
    "messing",
    "messy",
    "middle",
    "middleware",
    "million",
    "millions",
    "minaliit",
    "minamaliit",
    "miss",
    "missed",
    "missing",
    "misunderstood",
    "mood",
    "moode",
    "moodle",
    "muttering",
    "naa",
    "naaacknowledge",
    "naaakit",
    "naaaksaya",
    "naaannoy",
    "naaapektuhan",
    "naaapprecriate",
    "naaapreciate",
    "naaayos",
    "naabot",
    "naabsorb",
    "naabutan",
    "naaccept",
    "naachieve",
    "naaengganyong",
    "naanswer",
    "naappreciate",
    "naaprubahan",
    "naayos",
    "nabanggit",
    "nacall",
    "naccoconfuse",
    "nacoconnect",
    "nadaan",
    "naddrain",
    "nadedepress",
    "nadidiscuss",
    "nadidismiss",
    "nadiscuss",
    "naeelaborate",
    "naeengage",
    "naeenjoy",
    "naeexcite",
    "naeexcluded",
    "naeexplain",
    "naeexplian",
    "nafefeel",
    "naffollow",
    "naffrustrate",
    "nafollow",
    "nagadd",
    "nagannounce",
    "nagappear",
    "nagbanggit",
    "nagccrash",
    "nagcocommunicate",
    "nagcoconnect",
    "nagdidiscuss",
    "nagdiscuss",
    "nageeffort",
    "nageengage",
    "nageexplain",
    "nagffreeze",
    "nagfollow",
    "naggrade",
    "naggugroup",
    "nagiiba",
    "nagiimbento",
    "nagiinitiate",
    "nagiinteract",
    "nagiinterrupt",
    "nagkakaroon",
    "nagkaroon",
    "nagmamatter",
    "nagmessage",
    "nagmimeeting",
    "nagooccupy",
    "nagooverlap",
    "nagooverthink",
    "nagpaactivity",
    "nagpaalala",
    "nagpapapanood",
    "nagpass",
    "nagproceed",
    "nagrrun",
    "nagsshare",
    "nagsskip",
    "nagsspam",
    "nagsstart",
    "nagsstore",
    "nagsstrugggle",
    "nagsstruggke",
    "nagsstruggle",
    "nagsstutter",
    "nagstruggle",
    "nagsusuggest",
    "nagtaas",
    "nagtataas",
    "naguusap",
    "nagwwork",
    "nahappy",
    "naiiba",
    "naiignore",
    "naiilang",
    "naiimagine",
    "naiinis",
    "naiinterrupt",
    "naiintimidate",
    "naiintindihan",
    "naiinvest",
    "naiinvite",
    "naiinvolve",
    "naiipit",
    "naiirita",
    "naiisip",
    "naiistorbo",
    "naiiwan",
    "naiiwang",
    "naiiyak",
    "naillustrate",
    "naisasaalang",
    "naiuugnay",
    "nakaaapekto",
    "nakaattach",
    "nakaayos",
    "nakakaabala",
    "nakakaaffect",
    "nakakaalam",
    "nakakaannoy",
    "nakakaapekto",
    "nakakadisappoint",
    "nakakaembarass",
    "nakakafollow",
    "nakakahappy",
    "nakakairritate",
    "nakakaligtaan",
    "nakakapanliit",
    "nakakapressure",
    "nakakastress",
    "nakapaannoying",
    "nakaraan",
    "nakaraang",
    "nakasaad",
    "nakataas",
    "nakatanggap",
    "nakikipagcommunicate",
    "nameet",
    "namimiss",
    "namiss",
    "nanggaling",
    "nanonood",
    "naooverlook",
    "naooverthink",
    "naooverwrite",
    "napakaannoying",
    "napakahorrible",
    "napakaimpossible",
    "napakainappropriate",
    "napakasweet",
    "napakataas",
    "napakaunnecessary",
    "napakauseless",
    "napapakinggan",
    "napepressure",
    "narrate",
    "narrating",
    "narrator",
    "nasaan",
    "nasspark",
    "nasstress",
    "nasstuck",
    "nastress",
    "natanggap",
    "natatandaan",
    "natatanggap",
    "natatengga",
    "natengga",
    "naturally",
    "naunawaan",
    "nauubos",
    "nauubusan",
    "nauugnay",
    "nauuna",
    "nauunahan",
    "nauunawaan",
    "necessarily",
    "necessary",
    "need",
    "needed",
    "needing",
    "needs",
    "nervousness",
    "niassign",
    "nilaan",
    "nilelesson",
    "nirerecommend",
    "nodding",
    "noon",
    "noong",
    "normally",
    "notebook",
    "null",
    "nyaahahaha",
    "obsessed",
    "occasional",
    "oddly",
    "off",
    "offer",
    "offered",
    "offering",
    "office",
    "official",
    "offset",
    "oo",
    "oon",
    "oop",
    "oopen",
    "ooverthink",
    "opportunities",
    "opportunity",
    "opposite",
    "overall",
    "overcall",
    "overlapping",
    "overlook",
    "overlooked",
    "overriding",
    "paa",
    "paalala",
    "paalis",
    "paang",
    "paano",
    "paanong",
    "paatras",
    "pagaargue",
    "pagaassociate",
    "pagappeal",
    "pagapply",
    "pagassemble",
    "pagbanggit",
    "pagcocollaborate",
    "pagcoconnect",
    "pagconnect",
    "pagdicuss",
    "pagdidiscuss",
    "pagdiscuss",
    "pageexplain",
    "paggamit",
    "pagganap",
    "paggawa",
    "paggegrade",
    "paggrade",
    "pagiinteract",
    "pagiinvolve",
    "pagkaantala",
    "pagkadull",
    "pagkaheartless",
    "pagkaimmature",
    "pagkainappropirate",
    "pagkakaalam",
    "pagkakaayos",
    "pagkakaroon",
    "paglaanan",
    "pagsscore",
    "pagsself",
    "pagtuunan",
    "paguupdate",
    "painfully",
    "pakikinggan",
    "pakinggan",
    "palatandaan",
    "palatandaang",
    "panggrupo",
    "panggulo",
    "paniniwalaan",
    "panonood",
    "papaano",
    "paraan",
    "paraang",
    "parallel",
    "pass",
    "passed",
    "passes",
    "passing",
    "passion",
    "passionate",
    "passive",
    "pataas",
    "pattern",
    "patterns",
    "peer",
    "personally",
    "pessimistic",
    "piazza",
    "pills",
    "pinafollow",
    "pinaggawa",
    "pinaghandaan",
    "pinagiintegrate",
    "pinagiisip",
    "pinagkakatiwalaan",
    "pinaguusapan",
    "pinakaangkop",
    "pinakaastig",
    "pinakachallenging",
    "pinakaessense",
    "pinakikinggan",
    "pinapaaccomplish",
    "pinapafeel",
    "pinapakinggan",
    "pinapanood",
    "pinaproceed",
    "pinnacle",
    "pipiliin",
    "pisses",
    "pissy",
    "pitfall",
    "pitfalls",
    "planned",
    "planning",
    "plotting",
    "plugging",
    "pointless",
    "pooling",
    "poorer",
    "poorly",
    "possess",
    "possible",
    "possibly",
    "ppt",
    "preprocessing",
    "pressure",
    "pressured",
    "pretty",
    "proceed",
    "process",
    "processes",
    "processing",
    "processor",
    "professional",
    "professor",
    "professors",
    "programmed",
    "programmer",
    "programmers",
    "programmin",
    "programming",
    "progress",
    "progresses",
    "progression",
    "progressively",
    "proof",
    "proofs",
    "prrofs",
    "pull",
    "pumass",
    "putting",
    "puzzle",
    "queriess",
    "quizzes",
    "really",
    "recall",
    "recapping",
    "recommend",
    "recommendations",
    "recommended",
    "recurrence",
    "referred",
    "resubmission",
    "riddled",
    "rolled",
    "room",
    "rooms",
    "root",
    "roots",
    "running",
    "saakin",
    "saan",
    "saang",
    "saloobin",
    "sanggunian",
    "scanner",
    "scanning",
    "scattered",
    "school",
    "schoolers",
    "scool",
    "scoresheet",
    "screen",
    "screens",
    "screenshot",
    "screenshots",
    "scroll",
    "scrolling",
    "seamless",
    "see",
    "seeing",
    "seek",
    "seem",
    "seemed",
    "seemingly",
    "seems",
    "seen",
    "senseless",
    "serverless",
    "session",
    "sessions",
    "setting",
    "settled",
    "shallow",
    "sheesh",
    "sheet",
    "sheets",
    "shell",
    "shoot",
    "shuffling",
    "silly",
    "sinusuggest",
    "sitting",
    "skills",
    "skipped",
    "sleep",
    "small",
    "smaller",
    "smooth",
    "smoothly",
    "snapped",
    "snappy",
    "snippets",
    "snobber",
    "soon",
    "sooner",
    "sorry",
    "spamming",
    "spanning",
    "specially",
    "specifically",
    "speed",
    "speeds",
    "speedy",
    "sstem",
    "staff",
    "stalls",
    "steer",
    "still",
    "stopped",
    "stress",
    "stressed",
    "stressful",
    "structurally",
    "struggle",
    "struggled",
    "struggles",
    "struggling",
    "stuff",
    "stutter",
    "stutters",
    "subclasses",
    "submission",
    "submissions",
    "submitted",
    "submitting",
    "subnetting",
    "succeed",
    "successful",
    "sudden",
    "suddenly",
    "suffer",
    "suffered",
    "suffering",
    "suffers",
    "suggest",
    "suggested",
    "suggesting",
    "suggestion",
    "suggestions",
    "suggests",
    "summary",
    "summation",
    "summations",
    "support",
    "supporting",
    "supportive",
    "supports",
    "supposed",
    "suriin",
    "surroundings",
    "swallow",
    "sweet",
    "syllabus",
    "taas",
    "tandaan",
    "tanggal",
    "tanggalin",
    "tanggaling",
    "tanggap",
    "tanggapin",
    "tanggihan",
    "tapping",
    "tasteless",
    "tataas",
    "tatanggap",
    "tatanggapin",
    "teammates",
    "technically",
    "tell",
    "telling",
    "tells",
    "tengga",
    "terrible",
    "terror",
    "textbook",
    "textbooks",
    "theoretically",
    "three",
    "throttling",
    "tiisin",
    "tinaggap",
    "tinanggap",
    "tinanggihan",
    "tinatanggap",
    "tinatanggihan",
    "tinitiis",
    "toggle",
    "too",
    "took",
    "tool",
    "tools",
    "tossed",
    "totally",
    "totoo",
    "totoong",
    "tree",
    "trees",
    "troubleshoot",
    "troubleshooting",
    "tumaas",
    "tumanggap",
    "tumataas",
    "tutuusin",
    "umaabot",
    "umaagree",
    "umaalis",
    "umaasa",
    "umaayon",
    "umattend",
    "umiikot",
    "umiirap",
    "unapproachable",
    "understood",
    "unless",
    "unneccessarily",
    "unnecessarily",
    "unnecessary",
    "unnoticed",
    "unprofessional",
    "unprofessionalism",
    "usefulness",
    "useless",
    "usually",
    "uugnay",
    "uugnayan",
    "uulat",
    "uulit",
    "uulitin",
    "uumpisang",
    "uunahin",
    "uunahing",
    "uunmute",
    "uupo",
    "uusap",
    "uusapan",
    "verbally",
    "virtually",
    "volunteer",
    "wahahaah",
    "wall",
    "walls",
    "waterfall",
    "waterloo",
    "weakness",
    "weaknesses",
    "week",
    "weekend",
    "weekly",
    "weeks",
    "well",
    "will",
    "willing",
    "wood",
    "wooden",
    "worry",
    "wrapping",
    "written",
    "yapper",
    "yelled",
    "zoom",
}


def is_valid_word(word: str) -> bool:
    return word.lower() in SEED_VOCABULARY


def remove_noise(text: str) -> str:
    """Strips URLs, tags, hashtags, and emojis."""
    cleaned = URL_PATTERN.sub("", text)
    cleaned = TAG_PATTERN.sub("", cleaned)
    cleaned = HASHTAG_PATTERN.sub("", cleaned)
    cleaned = EMOJI_PATTERN.sub("", cleaned)
    return cleaned


def normalize_vowels(text: str) -> str:
    """Reduces repeated letters (e.g., 'yessss' -> 'yes') using vocabulary lookup."""

    def replace_match(match: re.Match) -> str:
        letter = match.group(1)
        offset = match.start()
        match_len = len(match.group(0))
        single_char_version = letter
        double_char_version = letter + letter

        # Find word boundaries around the match
        word_start = offset
        while word_start > 0 and (text[word_start - 1].isalnum() or text[word_start - 1] == "_"):
            word_start -= 1
        word_end = offset + match_len
        while word_end < len(text) and (text[word_end].isalnum() or text[word_end] == "_"):
            word_end += 1

        original_word = text[word_start:word_end]
        double_letter_word = (
            original_word[: offset - word_start]
            + double_char_version
            + original_word[offset + match_len - word_start :]
        ).lower()

        if is_valid_word(double_letter_word):
            return double_char_version

        return single_char_version

    return REPETITION_PATTERN.sub(replace_match, text)


def split_attached_punctuation(token: str):
    """Splits token into leading punctuation, core word, and trailing punctuation."""
    start = 0
    while start < len(token) and not (token[start].isalnum() or token[start] == "_"):
        start += 1
    end = len(token)
    while end > start and not (token[end - 1].isalnum() or token[end - 1] == "_"):
        end -= 1
    return token[:start], token[start:end], token[end:]


def expand_abbreviations(text: str) -> str:
    """Expands common abbreviations to full words using word-boundary single-pass tokenization."""
    chunks = re.split(r"(\s+)", text)
    result = []
    for chunk in chunks:
        if not chunk:
            continue
        if re.match(r"^\s+$", chunk):
            result.append(chunk)
            continue

        leading, core, trailing = split_attached_punctuation(chunk)
        full_word = ABBREVIATION_LOOKUP.get(core.lower())
        if full_word is None:
            result.append(chunk)
        else:
            result.append(leading + full_word + trailing)
    return "".join(result)


def normalize_whitespace(text: str) -> str:
    """Collapses whitespace and trims."""
    return re.sub(r"\s+", " ", text).strip()


def preprocess(text: str) -> str:
    """
    Cleans feedback text: removes noise, normalizes repetitions,
    expands abbreviations, trims whitespace.
    """
    if not isinstance(text, str):
        return ""
    after_noise = remove_noise(text)
    after_vowels = normalize_vowels(after_noise)
    after_abbrev = expand_abbreviations(after_vowels)
    cleaned = normalize_whitespace(after_abbrev)
    return cleaned
