/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as FacultyRouteImport } from './routes/_faculty'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthStudentRouteImport } from './routes/auth.student'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthFacultyRouteImport } from './routes/auth.faculty'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as FacultyHomeRouteImport } from './routes/_faculty.home'
import { Route as FacultyDashboardRouteImport } from './routes/_faculty.dashboard'
import { Route as FacultyArchivedRouteImport } from './routes/_faculty.archived'
import { Route as FacultyClassIdRouteImport } from './routes/_faculty.$classId'
import { Route as StudentStudentHomeRouteImport } from './routes/_student.student.home'
import { Route as FacultyDevSimulationRouteImport } from './routes/_faculty.dev.simulation'
import { Route as FacultyDevCompareModelsRouteImport } from './routes/_faculty.dev.compare-models'
import { Route as FacultyClassIdAnalysisSessionIdRouteImport } from './routes/_faculty.$classId.analysis.$sessionId'

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/_faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStudentRoute = AuthStudentRouteImport.update({
  id: '/auth/student',
  path: '/auth/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFacultyRoute = AuthFacultyRouteImport.update({
  id: '/auth/faculty',
  path: '/auth/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyHomeRoute = FacultyHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyDashboardRoute = FacultyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyArchivedRoute = FacultyArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyClassIdRoute = FacultyClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => FacultyRoute,
} as any)
const StudentStudentHomeRoute = StudentStudentHomeRouteImport.update({
  id: '/student/home',
  path: '/student/home',
  getParentRoute: () => StudentRoute,
} as any)
const FacultyDevSimulationRoute = FacultyDevSimulationRouteImport.update({
  id: '/dev/simulation',
  path: '/dev/simulation',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyDevCompareModelsRoute = FacultyDevCompareModelsRouteImport.update({
  id: '/dev/compare-models',
  path: '/dev/compare-models',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyClassIdAnalysisSessionIdRoute =
  FacultyClassIdAnalysisSessionIdRouteImport.update({
    id: '/analysis/$sessionId',
    path: '/analysis/$sessionId',
    getParentRoute: () => FacultyClassIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/$classId': typeof FacultyClassIdRouteWithChildren
  '/archived': typeof FacultyArchivedRoute
  '/dashboard': typeof FacultyDashboardRoute
  '/home': typeof FacultyHomeRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/faculty': typeof AuthFacultyRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/student': typeof AuthStudentRoute
  '/dev/compare-models': typeof FacultyDevCompareModelsRoute
  '/dev/simulation': typeof FacultyDevSimulationRoute
  '/student/home': typeof StudentStudentHomeRoute
  '/$classId/analysis/$sessionId': typeof FacultyClassIdAnalysisSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/$classId': typeof FacultyClassIdRouteWithChildren
  '/archived': typeof FacultyArchivedRoute
  '/dashboard': typeof FacultyDashboardRoute
  '/home': typeof FacultyHomeRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/faculty': typeof AuthFacultyRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/student': typeof AuthStudentRoute
  '/dev/compare-models': typeof FacultyDevCompareModelsRoute
  '/dev/simulation': typeof FacultyDevSimulationRoute
  '/student/home': typeof StudentStudentHomeRoute
  '/$classId/analysis/$sessionId': typeof FacultyClassIdAnalysisSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_faculty': typeof FacultyRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/_faculty/$classId': typeof FacultyClassIdRouteWithChildren
  '/_faculty/archived': typeof FacultyArchivedRoute
  '/_faculty/dashboard': typeof FacultyDashboardRoute
  '/_faculty/home': typeof FacultyHomeRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/faculty': typeof AuthFacultyRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/student': typeof AuthStudentRoute
  '/_faculty/dev/compare-models': typeof FacultyDevCompareModelsRoute
  '/_faculty/dev/simulation': typeof FacultyDevSimulationRoute
  '/_student/student/home': typeof StudentStudentHomeRoute
  '/_faculty/$classId/analysis/$sessionId': typeof FacultyClassIdAnalysisSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/$classId'
    | '/archived'
    | '/dashboard'
    | '/home'
    | '/auth/confirm'
    | '/auth/faculty'
    | '/auth/reset-password'
    | '/auth/student'
    | '/dev/compare-models'
    | '/dev/simulation'
    | '/student/home'
    | '/$classId/analysis/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/$classId'
    | '/archived'
    | '/dashboard'
    | '/home'
    | '/auth/confirm'
    | '/auth/faculty'
    | '/auth/reset-password'
    | '/auth/student'
    | '/dev/compare-models'
    | '/dev/simulation'
    | '/student/home'
    | '/$classId/analysis/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_faculty'
    | '/_student'
    | '/privacy-policy'
    | '/_faculty/$classId'
    | '/_faculty/archived'
    | '/_faculty/dashboard'
    | '/_faculty/home'
    | '/auth/confirm'
    | '/auth/faculty'
    | '/auth/reset-password'
    | '/auth/student'
    | '/_faculty/dev/compare-models'
    | '/_faculty/dev/simulation'
    | '/_student/student/home'
    | '/_faculty/$classId/analysis/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacultyRoute: typeof FacultyRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthFacultyRoute: typeof AuthFacultyRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthStudentRoute: typeof AuthStudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_faculty': {
      id: '/_faculty'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/student': {
      id: '/auth/student'
      path: '/auth/student'
      fullPath: '/auth/student'
      preLoaderRoute: typeof AuthStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/faculty': {
      id: '/auth/faculty'
      path: '/auth/faculty'
      fullPath: '/auth/faculty'
      preLoaderRoute: typeof AuthFacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_faculty/home': {
      id: '/_faculty/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof FacultyHomeRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/_faculty/dashboard': {
      id: '/_faculty/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof FacultyDashboardRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/_faculty/archived': {
      id: '/_faculty/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof FacultyArchivedRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/_faculty/$classId': {
      id: '/_faculty/$classId'
      path: '/$classId'
      fullPath: '/$classId'
      preLoaderRoute: typeof FacultyClassIdRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/_student/student/home': {
      id: '/_student/student/home'
      path: '/student/home'
      fullPath: '/student/home'
      preLoaderRoute: typeof StudentStudentHomeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_faculty/dev/simulation': {
      id: '/_faculty/dev/simulation'
      path: '/dev/simulation'
      fullPath: '/dev/simulation'
      preLoaderRoute: typeof FacultyDevSimulationRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/_faculty/dev/compare-models': {
      id: '/_faculty/dev/compare-models'
      path: '/dev/compare-models'
      fullPath: '/dev/compare-models'
      preLoaderRoute: typeof FacultyDevCompareModelsRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/_faculty/$classId/analysis/$sessionId': {
      id: '/_faculty/$classId/analysis/$sessionId'
      path: '/analysis/$sessionId'
      fullPath: '/$classId/analysis/$sessionId'
      preLoaderRoute: typeof FacultyClassIdAnalysisSessionIdRouteImport
      parentRoute: typeof FacultyClassIdRoute
    }
  }
}

interface FacultyClassIdRouteChildren {
  FacultyClassIdAnalysisSessionIdRoute: typeof FacultyClassIdAnalysisSessionIdRoute
}

const FacultyClassIdRouteChildren: FacultyClassIdRouteChildren = {
  FacultyClassIdAnalysisSessionIdRoute: FacultyClassIdAnalysisSessionIdRoute,
}

const FacultyClassIdRouteWithChildren = FacultyClassIdRoute._addFileChildren(
  FacultyClassIdRouteChildren,
)

interface FacultyRouteChildren {
  FacultyClassIdRoute: typeof FacultyClassIdRouteWithChildren
  FacultyArchivedRoute: typeof FacultyArchivedRoute
  FacultyDashboardRoute: typeof FacultyDashboardRoute
  FacultyHomeRoute: typeof FacultyHomeRoute
  FacultyDevCompareModelsRoute: typeof FacultyDevCompareModelsRoute
  FacultyDevSimulationRoute: typeof FacultyDevSimulationRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyClassIdRoute: FacultyClassIdRouteWithChildren,
  FacultyArchivedRoute: FacultyArchivedRoute,
  FacultyDashboardRoute: FacultyDashboardRoute,
  FacultyHomeRoute: FacultyHomeRoute,
  FacultyDevCompareModelsRoute: FacultyDevCompareModelsRoute,
  FacultyDevSimulationRoute: FacultyDevSimulationRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

interface StudentRouteChildren {
  StudentStudentHomeRoute: typeof StudentStudentHomeRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentStudentHomeRoute: StudentStudentHomeRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacultyRoute: FacultyRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthFacultyRoute: AuthFacultyRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthStudentRoute: AuthStudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
