/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as FacultyRouteImport } from './routes/_faculty'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginStudentRouteImport } from './routes/login.student'
import { Route as LoginFacultyRouteImport } from './routes/login.faculty'
import { Route as FacultyHomeRouteImport } from './routes/_faculty.home'
import { Route as FacultyDashboardRouteImport } from './routes/_faculty.dashboard'
import { Route as FacultyArchivedRouteImport } from './routes/_faculty.archived'
import { Route as FacultyClassIdRouteImport } from './routes/_faculty.$classId'
import { Route as StudentStudentHomeRouteImport } from './routes/_student.student.home'
import { Route as StudentStudentSubmitSessionIdRouteImport } from './routes/_student.student.submit.$sessionId'
import { Route as FacultyClassIdAnalysisSessionIdRouteImport } from './routes/_faculty.$classId.analysis.$sessionId'

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/_faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginStudentRoute = LoginStudentRouteImport.update({
  id: '/login/student',
  path: '/login/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginFacultyRoute = LoginFacultyRouteImport.update({
  id: '/login/faculty',
  path: '/login/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyHomeRoute = FacultyHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyDashboardRoute = FacultyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyArchivedRoute = FacultyArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyClassIdRoute = FacultyClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => FacultyRoute,
} as any)
const StudentStudentHomeRoute = StudentStudentHomeRouteImport.update({
  id: '/student/home',
  path: '/student/home',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentSubmitSessionIdRoute =
  StudentStudentSubmitSessionIdRouteImport.update({
    id: '/student/submit/$sessionId',
    path: '/student/submit/$sessionId',
    getParentRoute: () => StudentRoute,
  } as any)
const FacultyClassIdAnalysisSessionIdRoute =
  FacultyClassIdAnalysisSessionIdRouteImport.update({
    id: '/analysis/$sessionId',
    path: '/analysis/$sessionId',
    getParentRoute: () => FacultyClassIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/$classId': typeof FacultyClassIdRouteWithChildren
  '/archived': typeof FacultyArchivedRoute
  '/dashboard': typeof FacultyDashboardRoute
  '/home': typeof FacultyHomeRoute
  '/login/faculty': typeof LoginFacultyRoute
  '/login/student': typeof LoginStudentRoute
  '/student/home': typeof StudentStudentHomeRoute
  '/$classId/analysis/$sessionId': typeof FacultyClassIdAnalysisSessionIdRoute
  '/student/submit/$sessionId': typeof StudentStudentSubmitSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/$classId': typeof FacultyClassIdRouteWithChildren
  '/archived': typeof FacultyArchivedRoute
  '/dashboard': typeof FacultyDashboardRoute
  '/home': typeof FacultyHomeRoute
  '/login/faculty': typeof LoginFacultyRoute
  '/login/student': typeof LoginStudentRoute
  '/student/home': typeof StudentStudentHomeRoute
  '/$classId/analysis/$sessionId': typeof FacultyClassIdAnalysisSessionIdRoute
  '/student/submit/$sessionId': typeof StudentStudentSubmitSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_faculty': typeof FacultyRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/_faculty/$classId': typeof FacultyClassIdRouteWithChildren
  '/_faculty/archived': typeof FacultyArchivedRoute
  '/_faculty/dashboard': typeof FacultyDashboardRoute
  '/_faculty/home': typeof FacultyHomeRoute
  '/login/faculty': typeof LoginFacultyRoute
  '/login/student': typeof LoginStudentRoute
  '/_student/student/home': typeof StudentStudentHomeRoute
  '/_faculty/$classId/analysis/$sessionId': typeof FacultyClassIdAnalysisSessionIdRoute
  '/_student/student/submit/$sessionId': typeof StudentStudentSubmitSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/$classId'
    | '/archived'
    | '/dashboard'
    | '/home'
    | '/login/faculty'
    | '/login/student'
    | '/student/home'
    | '/$classId/analysis/$sessionId'
    | '/student/submit/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/$classId'
    | '/archived'
    | '/dashboard'
    | '/home'
    | '/login/faculty'
    | '/login/student'
    | '/student/home'
    | '/$classId/analysis/$sessionId'
    | '/student/submit/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_faculty'
    | '/_student'
    | '/privacy-policy'
    | '/_faculty/$classId'
    | '/_faculty/archived'
    | '/_faculty/dashboard'
    | '/_faculty/home'
    | '/login/faculty'
    | '/login/student'
    | '/_student/student/home'
    | '/_faculty/$classId/analysis/$sessionId'
    | '/_student/student/submit/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacultyRoute: typeof FacultyRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  LoginFacultyRoute: typeof LoginFacultyRoute
  LoginStudentRoute: typeof LoginStudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_faculty': {
      id: '/_faculty'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/student': {
      id: '/login/student'
      path: '/login/student'
      fullPath: '/login/student'
      preLoaderRoute: typeof LoginStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/faculty': {
      id: '/login/faculty'
      path: '/login/faculty'
      fullPath: '/login/faculty'
      preLoaderRoute: typeof LoginFacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_faculty/home': {
      id: '/_faculty/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof FacultyHomeRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/_faculty/dashboard': {
      id: '/_faculty/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof FacultyDashboardRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/_faculty/archived': {
      id: '/_faculty/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof FacultyArchivedRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/_faculty/$classId': {
      id: '/_faculty/$classId'
      path: '/$classId'
      fullPath: '/$classId'
      preLoaderRoute: typeof FacultyClassIdRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/_student/student/home': {
      id: '/_student/student/home'
      path: '/student/home'
      fullPath: '/student/home'
      preLoaderRoute: typeof StudentStudentHomeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/submit/$sessionId': {
      id: '/_student/student/submit/$sessionId'
      path: '/student/submit/$sessionId'
      fullPath: '/student/submit/$sessionId'
      preLoaderRoute: typeof StudentStudentSubmitSessionIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_faculty/$classId/analysis/$sessionId': {
      id: '/_faculty/$classId/analysis/$sessionId'
      path: '/analysis/$sessionId'
      fullPath: '/$classId/analysis/$sessionId'
      preLoaderRoute: typeof FacultyClassIdAnalysisSessionIdRouteImport
      parentRoute: typeof FacultyClassIdRoute
    }
  }
}

interface FacultyClassIdRouteChildren {
  FacultyClassIdAnalysisSessionIdRoute: typeof FacultyClassIdAnalysisSessionIdRoute
}

const FacultyClassIdRouteChildren: FacultyClassIdRouteChildren = {
  FacultyClassIdAnalysisSessionIdRoute: FacultyClassIdAnalysisSessionIdRoute,
}

const FacultyClassIdRouteWithChildren = FacultyClassIdRoute._addFileChildren(
  FacultyClassIdRouteChildren,
)

interface FacultyRouteChildren {
  FacultyClassIdRoute: typeof FacultyClassIdRouteWithChildren
  FacultyArchivedRoute: typeof FacultyArchivedRoute
  FacultyDashboardRoute: typeof FacultyDashboardRoute
  FacultyHomeRoute: typeof FacultyHomeRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyClassIdRoute: FacultyClassIdRouteWithChildren,
  FacultyArchivedRoute: FacultyArchivedRoute,
  FacultyDashboardRoute: FacultyDashboardRoute,
  FacultyHomeRoute: FacultyHomeRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

interface StudentRouteChildren {
  StudentStudentHomeRoute: typeof StudentStudentHomeRoute
  StudentStudentSubmitSessionIdRoute: typeof StudentStudentSubmitSessionIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentStudentHomeRoute: StudentStudentHomeRoute,
  StudentStudentSubmitSessionIdRoute: StudentStudentSubmitSessionIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacultyRoute: FacultyRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  LoginFacultyRoute: LoginFacultyRoute,
  LoginStudentRoute: LoginStudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
